---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Harvest Shiny Application

--------------------------------------------------------------------------------

## Quick install and run

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


To install the Shiny app in an Rstudio session please use the following code. 

***Please note, that in R, code that is preceded by a # is not run (we often use the # symbol to write in non-code comments). You can run a line of code that is preceded by a # by deleting the # symbol.***

```{r setup}
list.of.packages <- c("devtools")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
library(devtools)

```



```{r, eval=FALSE }
devtools::install_github("DrMattG/HarvestGolem")
```


```{r load library}
library(HarvestGolem)

```


--------------------------------------------------------------------------------

### Run the app

The package has one function (which launches the Shiny App locally). 

To launch the App type this code in to the Console after you have loaded the library:
```{r eval=FALSE}

HarvestGolem::run_app()

```

