---
title: "HarvestGolem"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{HarvestGolem}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# Harvest Shiny Application

--------------------------------------------------------------------------------

## Quick install and run

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval=FALSE}
list.of.packages <- c("devtools")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
library(devtools)
#devtools::install_github("DrMattG/HarvestGolem")
# The repository is currently locked as private and this will code will give an error
# Error: Failed to install 'HarvestGolem' from GitHub: HTTP error 404. Not Found Did you spell the repo owner (`DrMattG`)
# and repo name (`HarvestGolem`) correctly? - If spelling is correct, check that you have the required permissions to access the repo.

```



To install the Shiny app in an Rstudio session please use the following code. 

***Please note, that in R, code that is preceeded by a # is not run (we often use the # symbol to write in non-code comments). You can run a line of code that is preceeded by a # by deleting the # symbol.***



```{r load library}
library(HarvestGolem)

```


--------------------------------------------------------------------------------

### Run the app

The package has one function (which launches the Shiny App locally) with an option of either a female-only predictive model or a two-sex, four-age class predictive model. [Link to assessment of these two models]

To run the female-only model type this code in to the Console after you have loaded the library:
```{r eval=FALSE}

run_app()

```

